// <auto-generated />
using CrudAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudAPI.Migrations
{
    [DbContext(typeof(SQLiteDBContext))]
    [Migration("20220922083853_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("CrudAPI.Models.Department", b =>
                {
                    b.Property<int>("Dno")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("dno");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Dno")
                        .HasName("Pk_dno");

                    b.ToTable("department");
                });

            modelBuilder.Entity("CrudAPI.Models.Employee", b =>
                {
                    b.Property<int>("Eno")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("eno");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<int>("Dno")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("dno");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Eno")
                        .HasName("Pk_eno");

                    b.HasIndex("Dno");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("CrudAPI.Models.Person", b =>
                {
                    b.Property<int>("Sno")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("sno");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Sno")
                        .HasName("Pk_sno");

                    b.ToTable("people");
                });

            modelBuilder.Entity("CrudAPI.Models.Employee", b =>
                {
                    b.HasOne("CrudAPI.Models.Department", "Dept")
                        .WithMany("Employees")
                        .HasForeignKey("Dno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("CrudAPI.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
